theme: jekyll-theme-minimal
title: Microdata Citation Explorer project
description: Description of "Automating Microdata Citation Detection". a project completed with the World Bank-UNHCR Joint Data Center on Forced Displacement
